# Generated by Django 4.2.2 on 2023-06-20 10:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name: ')),
                ('description', models.TextField(max_length=255, verbose_name='Description: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name: ')),
                ('description', models.TextField(max_length=255, verbose_name='Description: ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boys.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
