# Generated by Django 4.2.2 on 2023-06-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='Boys',
        ),
        migrations.AlterModelOptions(
            name='boys',
            options={'verbose_name': 'Boy', 'verbose_name_plural': 'Boys'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
